/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP I5
 */
public class ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        MrRobot = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        nombrepelicula1 = new javax.swing.JLabel();
        nombrepelicula2 = new javax.swing.JLabel();
        pelicula2 = new javax.swing.JLabel();
        genero2 = new javax.swing.JLabel();
        pelicula3 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JLabel();
        genero3 = new javax.swing.JLabel();
        pelicula4 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peliculas para programadore");
        setSize(new java.awt.Dimension(480, 640));

        jPanel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        MrRobot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mr robot.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(MrRobot, gridBagConstraints);

        Titulo1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        Titulo1.setText("Titulo: Mr Robot");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        jPanel1.add(Titulo1, gridBagConstraints);

        nombrepelicula1.setFont(new java.awt.Font("Calibri Light", 3, 14)); // NOI18N
        nombrepelicula1.setText("Genero: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        jPanel1.add(nombrepelicula1, gridBagConstraints);

        nombrepelicula2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        nombrepelicula2.setText("Titulo : Ningun sistema es seguro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        jPanel1.add(nombrepelicula2, gridBagConstraints);

        pelicula2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hacker (2019) filmanity.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(pelicula2, gridBagConstraints);

        genero2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        genero2.setText("Genero: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        jPanel1.add(genero2, gridBagConstraints);

        pelicula3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hacker piratas informaticos.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(pelicula3, gridBagConstraints);

        nombre3.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        nombre3.setText("Titulo: Piratas informaticos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(nombre3, gridBagConstraints);

        genero3.setText("Genero: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 20);
        jPanel1.add(genero3, gridBagConstraints);

        pelicula4.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        pelicula4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anonymoys.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel1.add(pelicula4, gridBagConstraints);

        titulo4.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        titulo4.setText("Titulo: Anonymous");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        jPanel1.add(titulo4, gridBagConstraints);

        jLabel1.setText("Genero: Drama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        jPanel1.add(jLabel1, gridBagConstraints);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
            try {
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } catch (ClassNotFoundException ex) {
       // Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        //Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        // Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
        // Logger.getLogger(ventana.class.getName()).log(Level.SEVERE, null, ex);
    }
 
       
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
      
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MrRobot;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel genero2;
    private javax.swing.JLabel genero3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre3;
    private javax.swing.JLabel nombrepelicula1;
    private javax.swing.JLabel nombrepelicula2;
    private javax.swing.JLabel pelicula2;
    private javax.swing.JLabel pelicula3;
    private javax.swing.JLabel pelicula4;
    private javax.swing.JLabel titulo4;
    // End of variables declaration//GEN-END:variables
}
